"""Initial migration

Revision ID: 29a4280cfe50
Revises: 
Create Date: 2025-05-27 14:21:50.965481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a4280cfe50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_cat')
    )
    op.create_table('utilisateurs',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=128), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('isadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('etablissements',
    sa.Column('id_etab', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id_cat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cat'], ['categories.id_cat'], ),
    sa.PrimaryKeyConstraint('id_etab')
    )
    op.create_table('retours',
    sa.Column('id_retour', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_etab', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_etab'], ['etablissements.id_etab'], ),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateurs.id_user'], ),
    sa.PrimaryKeyConstraint('id_retour')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retours')
    op.drop_table('etablissements')
    op.drop_table('utilisateurs')
    op.drop_table('categories')
    # ### end Alembic commands ###
